### ISSUE TITLE
Notes from my discussion with Cedar Hills city engineer

### ISSUE THREAD

**Issue by corbt** [byu-osl/city-issue-tracker#2]
This morning I met with the Cedar Hills city engineer.  The following notes are from our discussion.

The city currently tracks all work orders through a system called iWorq.  They would love it if we could interface with it so issues could be synchronized and they wouldn't have to double-enter data, but it doesn't look like they have an API so I don't think that's possible.

Currently, when an issue is reported they log it as a work order in iworq.  The secretary prints out a page for every work order and gives it to the maintenance crew.  Once they're done they return the paper with a signature and notes explaining what they did, and the secretary updates the iworq system to mark it as complete.

Currently they process 60-90 issues a month.  Of those they estimate ~30 are user-initiated and the rest are behind-the-scenes.  Examples of common user-reported issues are:
- Dead animals on the road
- Leaves
- Water coming down the hill (?)
- Potholes
- Streetlights out
- Fallen branches on city trails

Old, closed issues should be kept and be searchable (although the default should be to just search currently open issues) BUT should be automatically deleted after a year for legal liability reasons.

When an issue is created by a user, it should _not_ go live immediately.  Instead, the user should see some screen acknowledging that the issue has been submitted for review.  The system should then generate an email to the secretary alerting her that an issue has been filed.  She can then view the issue and click a button to "make public" if it is appropriate. At that point the system should send an email to the user telling them that the issue has been reviewed and is available.

The most recently reported issues should appear on the main page prominently. This will hopefully keep multiple citizens from all reporting the same issue.

Only the city should be able to comment/update the status on an issue (they're worried about arguments between citizens of the right way to address an issue).

When a user signs up there must be a terms/conditions box they have to check to create an account.  

When creating an issue citizens should be able to choose whether they want to be notified of updates or not.

The city should be able to see a list of all open issues (I think this view can be public too, all the issues are public anyway).

**Comment by ghuitster** [comment]
I noticed on [iWorQ's website](http://www.iworq.com/city-administration/citizen-requests/) they have a section about their citizen request product. It sounds like there is a web product that cities can add to their website to allow citizens to view the service requests for the city. Citizens can also submit requests through that web interface. Has Cedar Hills considered looking into using that citizen request product?

**Comment by corbt** [comment]
That's cool. No, I don't think they know about it.

2014-02-01 David Barley notifications@github.com:
